#!/bin/sh


# Either start or stop all the services in
# /etc/init.d and /etc/local/init.d, executing
# them in numerical order.

# Action: either "start" or "stop".
ACTION=$1


if [ "x$ACTION" = "xstop" ]; then
    SORTARG="-r"
else
    ACTION="start"
fi

INITFILES=`ls -1 /etc/init.d/S??* /etc/local/init.d/S??* 2>/dev/null | sed -e 's%\(.*\)/\([^/]*\)$%\2 \1/\2%' | sort -k 1 $SORTARG |cut -d ' ' -f 2`

for INITFILE in $INITFILES ; do

     # Ignore dangling symlinks (if any).
     [ ! -f "$INITFILE" ] && continue

     case "$INITFILE" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set $ACTION
		. $INITFILE
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $INITFILE $ACTION
	    ;;
    esac
done

